# frozen_string_literal: true

source "https://rubygems.org"

# This is the default theme used by GitHub Pages
gem "github-pages", group: :jekyll_plugins

# Additional Jekyll plugins
gem "jekyll-feed", "~> 0.12"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-seo-tag", "~> 2.6"
gem "jekyll-remote-theme", "~> 0.4"

# For local development
gem "webrick", "~> 1.7"